name: polymer_intl
description: An example of using Polymer with localized Intl messages
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  intl: '>=0.9.0 <0.13.0'
  polymer: '>=0.16.0 <1.1.0'
  test: any
transformers:
- polymer:
    entry_points: web/polymer_intl.html
- test/pub_serve:
    $include: test/**_test.dart
