name: polymer_intl
author: Dart Team <misc@dartlang.org>
description: An example of using Polymer with localized Intl messages
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  intl: '>=0.9.0 <0.13.0'
  polymer: ^1.0.0-rc.11
  web_components: ^0.12.0
transformers:
- polymer:
    entry_points:
    - web/polymer_intl.html
